### PR TITLE
Update for haproxy 2.1

### PR DESCRIPTION
**Pull request by thedoc31**
Doesn't look like I can push to a 2.1 branch in your repo, so if you need me to resubmit the PR once you've created a 2.1 branch, I am happy to do so.

### CODE REVIEW

**Comment by DBezemer** [comment]
@thedoc31 I will update soon and merge some other existing changes before that as well. If you can rebase against that upstream commit in branch 2.1 I'll be happy to merge your pull.

**Comment by DBezemer** [comment]
@thedoc31 branch 2.1 created, if you can merge changes and rebase against 2.1 I'll merge

**Comment by thedoc31** [comment]
@DBezemer I'm not seeing the 2.1 branch in your repo to rebase against 😕 --
image

**Comment by DBezemer** [comment]
@thedoc31 my bad, forgot to push

**Comment by thedoc31** [comment]
Closing per 2.1 rebase request and proper PR into the 2.1 branch.

**Pull request closed without merging**
