### PR TITLE
misc. fixes/improvements for debugging HAProxy

### PR DESCRIPTION
**Pull request by bugfood**
I need to debug a rare crash in haproxy. There are various things that need to be changed in order to be able to capture a useful core dump.

Please consider these patches for inclusion.

Thanks,
Corey

### CODE REVIEW

**Comment by DBezemer** [comment]
Overall I'm not against offering a debug install, but don't think it's a good option to change the default install to not strip the main binary. If you can address this (change on L133) and undo the inclusion of haproxy.init I'll include it for future packaging.

**Comment by bugfood** [comment]
Thanks for looking at this.

My understanding is that the RPM build process creates the debuginfo package by stripping the debug symbols from the binaries and saving them to a separate file.
https://docs.fedoraproject.org/en-US/packaging-guidelines/Debuginfo/

So, the haproxy binary itself does not contain the debug symbols even after my change:
```
[vagrant@default-centos6 rpm-haproxy]$ rpm -qa haproxy
haproxy-2.2.13-3.el6.x86_64
[vagrant@default-centos6 rpm-haproxy]$ file /usr/sbin/haproxy 
/usr/sbin/haproxy: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, stripped
```

Please let me know if I'm missing something wrong there.


What do you mean by "undo the inclusion of haproxy.init"? Do you mean you are opposed to the sourcing of /etc/sysconfig/haproxy?

**Comment by DBezemer** [comment]
the stripping part is fine as-is, the change in haproxy.init changes it from the default provide haproxy.init (see: https://github.com/haproxy/haproxy/blob/master/examples/haproxy.init which I don't want to maintain here. If you wish to use a custom init file you can fork this repo and build them customized for yourself. If you can revert that change I'll merge and include it for future use.

**Comment by bugfood** [comment]
Ah, I think I understand now. The file in this repo is the same as the one from upstream, and you don't want it to diverge from upstream. Is there any reason to not just have the RPM spec file install the file from upstream, then?

Anyway, I removed that particular commit from my branch.

Thanks,
Corey

**Comment by DBezemer** [comment]
@bugfood thanks, the spec file in this repo is the whole purpose of this repo. The upstream spec file does not build cross-release / cross distro.

**Comment by DBezemer** [comment]
merged, I had to update the check you did for testing whether the macro was specified, remember that spec files aren't shell syntax so building failed. All good now, added credits in the readme as well.

**Comment by bugfood** [comment]
Thank you.

For the init script, I can explain what I meant by a PR:
https://github.com/DBezemer/rpm-haproxy/pull/39

**Pull request merged**
