### PR TITLE
setup for HAProxy 1.8.3

### PR DESCRIPTION
**Pull request by khdevel**
- changed version to 1.8 in a Makefile
- setup systemd haproxy.service to handle 'Type=forking'
- removed 'systemd-wrapper' from SPEC

Changes to be committed:
	modified:   Makefile
	modified:   SOURCES/haproxy.service
	modified:   SPECS/haproxy.spec

### CODE REVIEW

**Comment by DBezemer** [comment]
Hi @khdevel thanks for the pull request. In order to remove the systemd-wrapper can you add a conditional build flag for USE_SYSTEMD=1 and change the systemd file to use -Ws?

Additionally I have not had a chance to validate that the included configuration files are still valid, so please be patient while I validate the whole build before releasing new RPMs

**Comment by khdevel** [comment]
Hi @DBezemer and thank you for the brief review. Regarding your requests the second one is fine, I will add the switch -Ws but the first one - conditional build is weird to me :) I assumed that you use branches which determines haproxy version. So we have 1.6 and 1.7 with specific tags which determines builds. My PR covers version 1.8 and I assumed that you will also put it into separate branch like 1.8 with tags like 1.8.3-1. In this case we do not need to have specific build flag which turns ON/OFF _systemd-wrapper_ because in version 1.8 there is no _systemd-wrapper_.
So, I assume that the conditional build for this version is unnecessary. Please correct me if I'm wrong :)

**Comment by pietervogelaar** [comment]
An important thing to sort out is that systemd-wrapper is started as root and then the actual haproxy process could be chrooted and run as haproxy user. In your systemd service file it will simply start as root which is less secure. But configuring `user=haproxy` and `group=haproxy` still not gives a chrooted environment I guess.

So I'm not sure how to do that part the right way.

**Comment by DBezemer** [comment]
@khdevel the reason for the conditional build is that I build for both CentOS 6 and 7, and on CentOS 6 there is no systemd

**Comment by khdevel** [comment]
@DBezemer sorry for such long delay in my update but I could not find a time for it :/ but finally I make it and I hope it is done right.
  - the USE_SYSTEMD flag was added into the _SPECS/haproxy.spec_ and it seems to work fine, below is the part of the compilation log
```
+ systemd_opts=USE_SYSTEMD=1
+ /usr/bin/make -j8 CPU=generic TARGET=linux2628 USE_SYSTEMD=1 USE_OPE
```
  - I rewritten a _SOURCES/haproxy.service_ to be more pro and flexible. It contains the option you wanted *(-Ws)*
```
ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE $OPTIONS
```
  - to handle compilaton for systemd I had to add additional package into the _Makefile_, a *systemd-devel*
  - I also updated the VERSION to 1.8.3, which is now the current

Now the package properly compiles itself and installation is successful. Even the _systemctl reload haproxy_ works properly now!

**Comment by DBezemer** [comment]
@khdevel thanks for the update I'll merge and make some more changes and then release the updated RPMs for 1.8.4

**Pull request merged**
