### PR TITLE
enabled TFO support in HAProxy for amzn1 kernels

### PR DESCRIPTION
**Pull request by jazzl0ver**
please, merge

### CODE REVIEW

**Comment by DBezemer** [comment]
@jazzl0ver what's the kernel version in Amazon Linux? TFO is only supported from kernel 3.7 onwards

**Comment by jazzl0ver** [comment]
```
# uname -r
4.14.123-86.109.amzn1.x86_64
```

**Comment by DBezemer** [comment]
Excellent, so then both NS=1 and TFO=1 can be used like on el7
Would you mind changing the syslog templates to the slightly altered format in the el6/el7 syslog files? The old format had issues were messages were still forwarded to /var/log/messages

**Comment by jazzl0ver** [comment]
> Would you mind changing the syslog templates to the slightly altered format in the el6/el7 syslog files? The old format had issues were messages were still forwarded to /var/log/messages

sure thing. what exactly would you like me to change to?

**Pull request merged**
