### PR TITLE
Update: build rpms in docker

### PR DESCRIPTION
**Pull request by till**
First of, thanks for publishing this repo. It's beautiful and it works! 🎉 

For us, I added a `Dockerfile` to build the rpms, I thought no need for `sudo` and I didn't want to provision a build server to install build deps etc..

Let me know what you think!

### CODE REVIEW

**Comment by DBezemer** [comment]
@till the sudo part is absolutely needed when building as non-privileged user on any OS. As you are already running 
```
CMD ["make", "build"]
```
there is no need to remove the sudo command from the Makefile since the install_prereq isn't called in your Dockerfile. I'm happy to merge if you remove this change.

**Comment by till** [comment]
@DBezemer yeah, it's a bit odd...

I removed it because of this:
https://github.com/DBezemer/rpm-haproxy/blob/0bada68e69ce126e311ca9e068cce3953617e79d/Makefile#L33

So, this is called when I `make build`. And I didn't need/want a sudo setup in Docker.

**Comment by till** [comment]
@DBezemer any thoughts for a workaround?

**Comment by DBezemer** [comment]
@till you can extend the recent merge by Davasny for LUA support and make the install_prereq default but optional (something like a make NO_SUDO=1) flag which then does not use sudo for the install_prereq

**Comment by till** [comment]
@DBezemer I'll have a look some time this week!

**Comment by till** [comment]
Sorry, I forgot about this pull-request! Thank you for integrating!

**Comment by DBezemer** [comment]
@till no worries, I optimized the build cycle a bit so only the RPMs are output to local disk and the whole execution can run with SElinux enabled. Hope it matches what you expected for this feature.

**Pull request closed without merging**
